spring.application.name=TarefaModulo40

# Conexao com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/tarefa_mod_40
spring.datasource.username=postgres
spring.datasource.password=1234

# Manter os dados e mostrar o SQL no console
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Liberar o Actuator para monitoramento
management.endpoints.web.exposure.include=*